version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - log_volume:/rails/log
      - tmp_volume:/rails/tmp

volumes:
  log_volume:
  tmp_volume:
